### ISSUE TITLE
API_offline

### ISSUE THREAD

**Issue by rpalloni** [krosamont/shiny_bike#1]
It is not clear to me where input$interval is defined in interval <- max(as.numeric(input$interval), 90).
I suspect this is causing the **Error in filter_impl: Result must have length 74, not 0** when running the app locally

**Comment by krosamont** [comment]
Hello Roberto,

Thank you for your message, I will check the code and I will correct the problem :)
But first, you should have an API key (you can have one on the following link) :
https://developer.jcdecaux.com/#/opendata/vls?page=getstarted
 
Then you should run the code data_dist.R and finally, you should check the path.

Best regards,
Kevin

**Comment by rpalloni** [comment]
Already done as in comment. App is running but getting warning and errors in R console

**Comment by krosamont** [comment]
you're right that I have to remove **input$interval** but  **Error in filter_impl: Result must have length 74, not 0** seems to be related to dplyr
